services:
    db:
        image: mongo:latest
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - 27017:27017
        volumes:
            - ./home/ubuntu/data:/data/db
    backend:
        image: mansmooth/ascalon:latest
        restart: unless-stopped
        environment:
            - database_host=db
            - database_port=27017
            - database_name=${DB_NAME}
            - database_user=${MONGO_USER}
            - database_password=${MONGO_PASSWORD}
        ports:
            - 8000:3001
        links:
            - db
